"""
Данные для загрузки плана счетов КР (МСФО) и правил разноски.
Запускается через POST /api/posting/seed-chart
"""

CHART_OF_ACCOUNTS = [
    # РАЗДЕЛ 1: КРАТКОСРОЧНЫЕ АКТИВЫ
    {"code":"1000","name":"Краткосрочные активы","section":"1000","account_type":"active","level":1,"parent_code":None},
    {"code":"1100","name":"Денежные средства в кассе","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1110","name":"Денежные средства в нац. валюте (касса)","section":"1000","account_type":"active","level":3,"parent_code":"1100"},
    {"code":"1120","name":"Денежные средства в иностр. валюте (касса)","section":"1000","account_type":"active","level":3,"parent_code":"1100"},
    {"code":"1130","name":"Денежные документы","section":"1000","account_type":"active","level":3,"parent_code":"1100"},
    {"code":"1140","name":"Денежные эквиваленты","section":"1000","account_type":"active","level":3,"parent_code":"1100"},
    {"code":"1200","name":"Денежные средства в банке","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1210","name":"Счета в национальной валюте (банк)","section":"1000","account_type":"active","level":3,"parent_code":"1200"},
    {"code":"1220","name":"Счета в иностр. валюте в местных банках","section":"1000","account_type":"active","level":3,"parent_code":"1200"},
    {"code":"1230","name":"Счета в зарубежных банках","section":"1000","account_type":"active","level":3,"parent_code":"1200"},
    {"code":"1240","name":"Денежные средства в банках, ограниченные к использованию","section":"1000","account_type":"active","level":3,"parent_code":"1200"},
    {"code":"1250","name":"Денежные средства в пути","section":"1000","account_type":"active","level":3,"parent_code":"1200"},
    {"code":"1300","name":"Краткосрочные инвестиции","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1310","name":"Долговые ценные бумаги (краткосрочные)","section":"1000","account_type":"active","level":3,"parent_code":"1300"},
    {"code":"1320","name":"Долевые ценные бумаги (краткосрочные)","section":"1000","account_type":"active","level":3,"parent_code":"1300"},
    {"code":"1330","name":"Кредиты и займы выданные (краткосрочные)","section":"1000","account_type":"active","level":3,"parent_code":"1300"},
    {"code":"1340","name":"Депозитные вклады (краткосрочные)","section":"1000","account_type":"active","level":3,"parent_code":"1300"},
    {"code":"1400","name":"Счета к получению (торговая дебиторская задолженность)","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1410","name":"Счета к получению от покупателей","section":"1000","account_type":"active","level":3,"parent_code":"1400"},
    {"code":"1420","name":"Векселя к получению","section":"1000","account_type":"active","level":3,"parent_code":"1400"},
    {"code":"1490","name":"Резерв на безнадёжные долги по счетам к получению","section":"1000","account_type":"active","level":3,"parent_code":"1400"},
    {"code":"1500","name":"Дебиторская задолженность по прочим операциям","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1510","name":"Авансы выданные поставщикам","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1520","name":"Дебиторская задолженность сотрудников","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1530","name":"Налоги, оплаченные авансом","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1540","name":"НДС к возмещению","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1560","name":"Расходы будущих периодов","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1590","name":"Прочая краткосрочная дебиторская задолженность","section":"1000","account_type":"active","level":3,"parent_code":"1500"},
    {"code":"1600","name":"Товарно-материальные запасы (ТМЗ)","section":"1000","account_type":"active","level":2,"parent_code":"1000"},
    {"code":"1610","name":"Сырьё и материалы","section":"1000","account_type":"active","level":3,"parent_code":"1600"},
    {"code":"1620","name":"Незавершённое производство","section":"1000","account_type":"active","level":3,"parent_code":"1600"},
    {"code":"1630","name":"Готовая продукция","section":"1000","account_type":"active","level":3,"parent_code":"1600"},
    {"code":"1640","name":"Товары для перепродажи","section":"1000","account_type":"active","level":3,"parent_code":"1600"},
    {"code":"1650","name":"Прочие запасы","section":"1000","account_type":"active","level":3,"parent_code":"1600"},
    # РАЗДЕЛ 2: ДОЛГОСРОЧНЫЕ АКТИВЫ
    {"code":"2000","name":"Долгосрочные активы","section":"2000","account_type":"active","level":1,"parent_code":None},
    {"code":"2100","name":"Основные средства","section":"2000","account_type":"active","level":2,"parent_code":"2000"},
    {"code":"2110","name":"Земля","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2120","name":"Здания и сооружения","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2130","name":"Машины и оборудование","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2140","name":"Транспортные средства","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2150","name":"Прочие основные средства","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2190","name":"Накопленная амортизация ОС","section":"2000","account_type":"active","level":3,"parent_code":"2100"},
    {"code":"2200","name":"Нематериальные активы","section":"2000","account_type":"active","level":2,"parent_code":"2000"},
    {"code":"2210","name":"Патенты, лицензии, товарные знаки","section":"2000","account_type":"active","level":3,"parent_code":"2200"},
    {"code":"2220","name":"Программное обеспечение","section":"2000","account_type":"active","level":3,"parent_code":"2200"},
    {"code":"2290","name":"Накопленная амортизация НМА","section":"2000","account_type":"active","level":3,"parent_code":"2200"},
    # РАЗДЕЛ 3: КРАТКОСРОЧНЫЕ ОБЯЗАТЕЛЬСТВА
    {"code":"3000","name":"Краткосрочные обязательства","section":"3000","account_type":"passive","level":1,"parent_code":None},
    {"code":"3100","name":"Краткосрочные финансовые обязательства","section":"3000","account_type":"passive","level":2,"parent_code":"3000"},
    {"code":"3110","name":"Краткосрочные кредиты банков","section":"3000","account_type":"passive","level":3,"parent_code":"3100"},
    {"code":"3120","name":"Краткосрочные займы полученные","section":"3000","account_type":"passive","level":3,"parent_code":"3100"},
    {"code":"3200","name":"Счета к оплате (торговая кредиторская задолженность)","section":"3000","account_type":"passive","level":2,"parent_code":"3000"},
    {"code":"3210","name":"Счета к оплате поставщикам","section":"3000","account_type":"passive","level":3,"parent_code":"3200"},
    {"code":"3220","name":"Векселя к оплате","section":"3000","account_type":"passive","level":3,"parent_code":"3200"},
    {"code":"3300","name":"Налоговые обязательства","section":"3000","account_type":"passive","level":2,"parent_code":"3000"},
    {"code":"3310","name":"Налог на прибыль к уплате","section":"3000","account_type":"passive","level":3,"parent_code":"3300"},
    {"code":"3320","name":"НДС к уплате","section":"3000","account_type":"passive","level":3,"parent_code":"3300"},
    {"code":"3330","name":"Налог с продаж к уплате","section":"3000","account_type":"passive","level":3,"parent_code":"3300"},
    {"code":"3390","name":"Прочие налоги и сборы к уплате","section":"3000","account_type":"passive","level":3,"parent_code":"3300"},
    {"code":"3400","name":"Обязательства по оплате труда","section":"3000","account_type":"passive","level":2,"parent_code":"3000"},
    {"code":"3410","name":"Задолженность по заработной плате","section":"3000","account_type":"passive","level":3,"parent_code":"3400"},
    {"code":"3420","name":"Задолженность по отчислениям в Социальный Фонд","section":"3000","account_type":"passive","level":3,"parent_code":"3400"},
    {"code":"3430","name":"Задолженность по НДФЛ (подоходный налог)","section":"3000","account_type":"passive","level":3,"parent_code":"3400"},
    {"code":"3500","name":"Прочие краткосрочные обязательства","section":"3000","account_type":"passive","level":2,"parent_code":"3000"},
    {"code":"3510","name":"Авансы полученные от покупателей","section":"3000","account_type":"passive","level":3,"parent_code":"3500"},
    {"code":"3520","name":"Доходы будущих периодов (краткосрочные)","section":"3000","account_type":"passive","level":3,"parent_code":"3500"},
    {"code":"3530","name":"Резервы предстоящих расходов","section":"3000","account_type":"passive","level":3,"parent_code":"3500"},
    {"code":"3590","name":"Прочие краткосрочные обязательства","section":"3000","account_type":"passive","level":3,"parent_code":"3500"},
    # РАЗДЕЛ 4: ДОЛГОСРОЧНЫЕ ОБЯЗАТЕЛЬСТВА
    {"code":"4000","name":"Долгосрочные обязательства","section":"4000","account_type":"passive","level":1,"parent_code":None},
    {"code":"4100","name":"Долгосрочные финансовые обязательства","section":"4000","account_type":"passive","level":2,"parent_code":"4000"},
    {"code":"4110","name":"Долгосрочные кредиты банков","section":"4000","account_type":"passive","level":3,"parent_code":"4100"},
    {"code":"4120","name":"Долгосрочные займы полученные","section":"4000","account_type":"passive","level":3,"parent_code":"4100"},
    {"code":"4300","name":"Отложенные налоговые обязательства","section":"4000","account_type":"passive","level":2,"parent_code":"4000"},
    {"code":"4310","name":"Отложенный налог на прибыль","section":"4000","account_type":"passive","level":3,"parent_code":"4300"},
    # РАЗДЕЛ 5: СОБСТВЕННЫЙ КАПИТАЛ
    {"code":"5000","name":"Собственный капитал","section":"5000","account_type":"passive","level":1,"parent_code":None},
    {"code":"5100","name":"Уставный капитал","section":"5000","account_type":"passive","level":2,"parent_code":"5000"},
    {"code":"5110","name":"Объявленный уставный капитал","section":"5000","account_type":"passive","level":3,"parent_code":"5100"},
    {"code":"5400","name":"Нераспределённая прибыль / непокрытый убыток","section":"5000","account_type":"passive","level":2,"parent_code":"5000"},
    {"code":"5410","name":"Нераспределённая прибыль прошлых лет","section":"5000","account_type":"passive","level":3,"parent_code":"5400"},
    {"code":"5420","name":"Нераспределённая прибыль отчётного года","section":"5000","account_type":"passive","level":3,"parent_code":"5400"},
    # РАЗДЕЛ 6: ДОХОДЫ
    {"code":"6000","name":"Доходы от операционной деятельности","section":"6000","account_type":"passive","level":1,"parent_code":None},
    {"code":"6100","name":"Доходы от реализации товаров и услуг","section":"6000","account_type":"passive","level":2,"parent_code":"6000"},
    {"code":"6110","name":"Доходы от реализации товаров","section":"6000","account_type":"passive","level":3,"parent_code":"6100"},
    {"code":"6120","name":"Доходы от реализации услуг","section":"6000","account_type":"passive","level":3,"parent_code":"6100"},
    {"code":"6200","name":"Прочие операционные доходы","section":"6000","account_type":"passive","level":2,"parent_code":"6000"},
    {"code":"6210","name":"Доходы от аренды","section":"6000","account_type":"passive","level":3,"parent_code":"6200"},
    {"code":"6220","name":"Доходы от курсовых разниц","section":"6000","account_type":"passive","level":3,"parent_code":"6200"},
    {"code":"6290","name":"Прочие операционные доходы","section":"6000","account_type":"passive","level":3,"parent_code":"6200"},
    {"code":"6300","name":"Доходы от финансовой деятельности","section":"6000","account_type":"passive","level":2,"parent_code":"6000"},
    {"code":"6310","name":"Процентные доходы","section":"6000","account_type":"passive","level":3,"parent_code":"6300"},
    # РАЗДЕЛ 7: РАСХОДЫ
    {"code":"7000","name":"Операционные расходы","section":"7000","account_type":"active","level":1,"parent_code":None},
    {"code":"7100","name":"Себестоимость реализации","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7110","name":"Себестоимость реализованных товаров","section":"7000","account_type":"active","level":3,"parent_code":"7100"},
    {"code":"7120","name":"Себестоимость реализованных услуг","section":"7000","account_type":"active","level":3,"parent_code":"7100"},
    {"code":"7200","name":"Расходы на реализацию (коммерческие)","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7210","name":"Расходы на рекламу и маркетинг","section":"7000","account_type":"active","level":3,"parent_code":"7200"},
    {"code":"7220","name":"Расходы на транспортировку и доставку","section":"7000","account_type":"active","level":3,"parent_code":"7200"},
    {"code":"7230","name":"Расходы на упаковку","section":"7000","account_type":"active","level":3,"parent_code":"7200"},
    {"code":"7290","name":"Прочие расходы на реализацию","section":"7000","account_type":"active","level":3,"parent_code":"7200"},
    {"code":"7300","name":"Административные и управленческие расходы","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7310","name":"Расходы на оплату труда (административные)","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7320","name":"Отчисления в Социальный Фонд (административные)","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7330","name":"Аренда офиса / склада","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7340","name":"Коммунальные услуги","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7350","name":"Связь и интернет","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7360","name":"Амортизация (административная)","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7370","name":"Юридические и аудиторские услуги","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7380","name":"Банковские услуги","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7390","name":"Прочие административные расходы","section":"7000","account_type":"active","level":3,"parent_code":"7300"},
    {"code":"7500","name":"Прочие операционные расходы","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7510","name":"Расходы от курсовых разниц","section":"7000","account_type":"active","level":3,"parent_code":"7500"},
    {"code":"7520","name":"Расходы по безнадёжным долгам","section":"7000","account_type":"active","level":3,"parent_code":"7500"},
    {"code":"7530","name":"Штрафы, пени, неустойки уплаченные","section":"7000","account_type":"active","level":3,"parent_code":"7500"},
    {"code":"7540","name":"Налоги (кроме налога на прибыль)","section":"7000","account_type":"active","level":3,"parent_code":"7500"},
    {"code":"7590","name":"Прочие операционные расходы","section":"7000","account_type":"active","level":3,"parent_code":"7500"},
    {"code":"7600","name":"Финансовые расходы","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7610","name":"Процентные расходы по кредитам и займам","section":"7000","account_type":"active","level":3,"parent_code":"7600"},
    {"code":"7700","name":"Расходы по налогу на прибыль","section":"7000","account_type":"active","level":2,"parent_code":"7000"},
    {"code":"7710","name":"Текущий налог на прибыль","section":"7000","account_type":"active","level":3,"parent_code":"7700"},
]

POSTING_RULES = [
    {"rule_name":"Покупка товаров у поставщика (кредит)","document_type":"invoice","operation_keywords":["товар","накладная","поставка","ТТН","спецификация","брюки","одежда","текстиль","импорт"],"debit_account":"1640","credit_account":"3210","description":"Поступление товаров: Дт Товары / Кт Счета к оплате","priority":90},
    {"rule_name":"Покупка сырья и материалов","document_type":"invoice","operation_keywords":["сырьё","материалы","запасы","комплектующие"],"debit_account":"1610","credit_account":"3210","description":"Поступление материалов: Дт Сырьё / Кт Счета к оплате","priority":80},
    {"rule_name":"Транспортные услуги (кредит)","document_type":"act","operation_keywords":["транспорт","перевозка","доставка","логистика","фрахт","экспедиция","грузоперевозка","CMR","ТТН"],"debit_account":"7220","credit_account":"3210","description":"Транспортные расходы: Дт 7220 / Кт 3210","priority":90},
    {"rule_name":"Таможенные сборы и пошлины","document_type":"receipt","operation_keywords":["таможня","таможенный сбор","пошлина","таможенное оформление","Манас"],"debit_account":"1640","credit_account":"1210","description":"Таможня включается в стоимость товара: Дт Товары / Кт Банк","priority":90},
    {"rule_name":"Аренда офиса / склада","document_type":"invoice","operation_keywords":["аренда","арендная плата","субаренда","найм помещения"],"debit_account":"7330","credit_account":"3210","description":"Аренда: Дт 7330 / Кт 3210","priority":85},
    {"rule_name":"Коммунальные услуги","document_type":"invoice","operation_keywords":["электроэнергия","водоснабжение","коммунальные","теплоснабжение","газ"],"debit_account":"7340","credit_account":"3210","description":"Коммунальные: Дт 7340 / Кт 3210","priority":85},
    {"rule_name":"Услуги связи и интернет","document_type":"invoice","operation_keywords":["связь","интернет","телефон","мобильная связь","IT"],"debit_account":"7350","credit_account":"3210","description":"Связь: Дт 7350 / Кт 3210","priority":85},
    {"rule_name":"Банковские комиссии","document_type":"bank_statement","operation_keywords":["комиссия банка","банковское обслуживание","РКО","инкассация"],"debit_account":"7380","credit_account":"1210","description":"Банк: Дт 7380 / Кт Расчётный счёт","priority":85},
    {"rule_name":"Страховые взносы","document_type":"invoice","operation_keywords":["страхование","страховая премия","страховой полис"],"debit_account":"7390","credit_account":"3210","description":"Страхование: Дт 7390 / Кт 3210","priority":80},
    {"rule_name":"Оплата поставщику с расчётного счёта","document_type":"payment_order","operation_keywords":["оплата","перечисление","платёжное поручение"],"debit_account":"3210","credit_account":"1210","description":"Оплата поставщику: Дт 3210 / Кт Банк","priority":90},
    {"rule_name":"Поступление оплаты от покупателя","document_type":"bank_statement","operation_keywords":["оплата от покупателя","поступление выручки","продажа"],"debit_account":"1210","credit_account":"6110","description":"Выручка: Дт Банк / Кт 6110","priority":90},
    {"rule_name":"Начисление заработной платы","document_type":"payroll","operation_keywords":["зарплата","заработная плата","оклад"],"debit_account":"7310","credit_account":"3410","description":"Зарплата: Дт 7310 / Кт 3410","priority":90},
    {"rule_name":"Отчисления в Социальный Фонд","document_type":"payroll","operation_keywords":["социальный фонд","соцфонд","страховые взносы"],"debit_account":"7320","credit_account":"3420","description":"Соцфонд: Дт 7320 / Кт 3420","priority":90},
    {"rule_name":"ЭСФ входящий — покупка товаров","document_type":"esf","operation_keywords":["ЭСФ","счёт-фактура","НДС входящий","товар"],"debit_account":"1640","credit_account":"3210","description":"ЭСФ товары: Дт 1640 / Кт 3210","priority":95},
    {"rule_name":"ЭСФ входящий — услуги","document_type":"esf","operation_keywords":["ЭСФ","счёт-фактура","услуги","работы"],"debit_account":"7390","credit_account":"3210","description":"ЭСФ услуги: Дт 7390 / Кт 3210","priority":80},
    {"rule_name":"Аванс поставщику","document_type":"payment_order","operation_keywords":["аванс","предоплата","100% предоплата"],"debit_account":"1510","credit_account":"1210","description":"Аванс поставщику: Дт 1510 / Кт Банк","priority":85},
]
